In [3]:
import numpy as np
a = np.array([1, 2, 3])
a


array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=complex)
b

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

In [6]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.empty((3, 3))

array([[ 1.13698106e-313,  0.00000000e+000,  6.90276899e-310],
       [ 2.20081250e-205,  6.90276899e-310,  6.90276899e-310],
       [-3.68866123e+158,  6.90276899e-310,  3.95252517e-322]])

In [10]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [11]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [12]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
def f1(i, j):
    return 3 * i + j


In [14]:
np.fromfunction(f1, (3, 4))

array([[0., 1., 2., 3.],
       [3., 4., 5., 6.],
       [6., 7., 8., 9.]])

In [15]:
np.fromfunction(f1, (3, 3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [16]:
print(np.arange(0, 3000, 1))

[   0    1    2 ... 2997 2998 2999]
