In [1]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
a + b

array([20, 31, 42, 53])

In [2]:
a - b

array([20, 29, 38, 47])

In [3]:
a * b

array([  0,  30,  80, 150])

In [4]:
a / b 

/tmp/ipykernel_27006/2587490937.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([        inf, 30.        , 20.        , 16.66666667])

In [5]:
a ** b

array([     1,     30,   1600, 125000])

In [6]:
a % b

/tmp/ipykernel_27006/2189094906.py:1: RuntimeWarning: divide by zero encountered in remainder
  a % b


array([0, 0, 0, 2])

In [7]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[1, 2], [3, 4], [5, 6]])
c + d

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [8]:
a + 1

array([21, 31, 41, 51])

In [9]:
a ** 3

array([  8000,  27000,  64000, 125000])

In [10]:
a < 35

array([ True,  True, False, False])

In [11]:
np.cos(a)

array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [12]:
np.arctan(a)

array([1.52083793, 1.53747533, 1.54580153, 1.55079899])

In [13]:
np.sinh(a)

array([2.42582598e+08, 5.34323729e+12, 1.17692633e+17, 2.59235276e+21])

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(a)

21

In [15]:
a.sum()

21

In [16]:
a.min()

1

In [17]:
a.max()

6

In [18]:
a.min(axis=0)

array([1, 2, 3])

In [19]:
a.min(axis=1)

array([1, 4])

In [20]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [21]:
a[1]

1

In [22]:
a[3:7]

array([ 27,  64, 125, 216])

In [23]:
a[3:7] = 8
a

array([  0,   1,   8,   8,   8,   8,   8, 343, 512, 729])

In [24]:
a[::-1]

array([729, 512, 343,   8,   8,   8,   8,   8,   1,   0])

In [25]:
del a[4:6]

ValueError: cannot delete array elements

In [27]:
for i in a:
    print(i ** (1/3))

0.0
1.0
2.0
2.0
2.0
2.0
2.0
6.999999999999999
7.999999999999999
8.999999999999998


In [28]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

In [29]:
b[2,3]

23

In [30]:
b[2][3] 

23

In [31]:
b[:,2]

array([ 2, 12, 22, 32, 42])

In [32]:
b[:2]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [33]:
b[1:3, : : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [34]:
b[-1]

array([40, 41, 42, 43])

In [35]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
a.shape

(2, 2, 3)

In [36]:
a[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [37]:
c[... ,2]

array([3, 6])

In [38]:
for row in a:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


In [39]:
for el in a.flat:
    print(el)

0
1
2
10
12
13
100
101
102
110
112
113


In [40]:
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [41]:
a.shape

(2, 2, 3)

In [42]:
a.ravel()

array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [43]:
a.shape = (6, 2) 

In [44]:
a

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [45]:
a.transpose()

array([[  0,   2,  12, 100, 102, 112],
       [  1,  10,  13, 101, 110, 113]])

In [46]:
a.reshape((3, 4))

array([[  0,   1,   2,  10],
       [ 12,  13, 100, 101],
       [102, 110, 112, 113]])

In [47]:
a

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [48]:
a.reshape((3, 4), order='F')

array([[  0, 100,   1, 101],
       [  2, 102,  10, 110],
       [ 12, 112,  13, 113]])

In [49]:
a.resize((2, 6))
a

array([[  0,   1,   2,  10,  12,  13],
       [100, 101, 102, 110, 112, 113]])

In [50]:
a.reshape((3, -1))

array([[  0,   1,   2,  10],
       [ 12,  13, 100, 101],
       [102, 110, 112, 113]])

In [51]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [53]:
np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [54]:
np.row_stack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [55]:
a = np.arange(12).reshape((2, 6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [56]:
np.hsplit(a, 3)

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

In [57]:
np.hsplit(a, (3, 4))

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[3],
        [9]]),
 array([[ 4,  5],
        [10, 11]])]

In [58]:
a = np.arange(12)
b = a  
b is a

True

In [59]:
b.shape = (3,4)  
a.shape

(3, 4)

In [60]:
c = a.view()
c is a

False

In [61]:
c.base is a

True

In [62]:
c.flags.owndata

False

In [63]:
c.shape = (2,6)  
a.shape

(3, 4)

In [64]:
c[0,4] = 1234  
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [65]:
s = a[:,1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [66]:
d = a.copy()  
d is a

False

In [67]:
d.base is a

False

In [68]:
d[0, 0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])