In [1]:
import numpy as np
import random
np.array([random.random() for i in range(10)])

array([0.75873123, 0.18915655, 0.85187124, 0.34951021, 0.21699654,
       0.22738547, 0.90212579, 0.43467592, 0.02552739, 0.90132939])

In [2]:
import numpy as np  
np.random

<module 'numpy.random' from '/home/fedor/anaconda3/lib/python3.9/site-packages/numpy/random/__init__.py'>

In [3]:
import numpy.random as rand  
rand

<module 'numpy.random' from '/home/fedor/anaconda3/lib/python3.9/site-packages/numpy/random/__init__.py'>

In [4]:
np.random.sample()

0.08195039027231188

In [5]:
np.random.sample(3)

array([0.11939919, 0.95734776, 0.48373478])

In [6]:
np.random.sample((2, 3))

array([[0.40133466, 0.91103545, 0.13198438],
       [0.7662508 , 0.87641639, 0.65176882]])

In [7]:
np.random.randint(0, 3, 10)

array([1, 0, 2, 1, 2, 0, 0, 2, 1, 2])

In [8]:
np.random.random_integers(0, 3, 10)

/tmp/ipykernel_27589/3188335668.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 3 + 1) instead
  np.random.random_integers(0, 3, 10)


array([0, 2, 3, 1, 0, 3, 3, 2, 0, 3])

In [9]:
np.random.randint(0, 3, (2, 10))

array([[2, 2, 2, 1, 2, 1, 1, 0, 0, 0],
       [2, 1, 1, 0, 1, 1, 0, 2, 2, 2]])

In [10]:
np.random.uniform(2, 8, (2, 10))

array([[4.39798921, 3.08723993, 4.29398452, 7.29022088, 5.57376762,
        5.65995277, 7.57738546, 4.3402579 , 2.44503265, 2.2633298 ],
       [3.16340916, 4.50745001, 3.37706069, 7.48107528, 6.29648805,
        2.23512403, 2.97903687, 2.70720771, 7.27967741, 3.11368367]])

In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.shuffle(a)
a

array([2, 9, 5, 4, 7, 3, 1, 0, 8, 6])

In [13]:
np.random.permutation(10)

array([1, 2, 9, 6, 4, 5, 3, 0, 8, 7])

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.random.choice(a, 10, p=[0.5, 0.25, 0.25, 0, 0, 0, 0, 0, 0, 0])

array([2, 1, 1, 1, 0, 1, 0, 1, 0, 1])

In [16]:
np.random.seed(1000)
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

In [17]:
np.random.seed(1000)
np.random.random(10)


array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

In [18]:
np.random.seed(1000)
state = np.random.get_state()
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

In [19]:
np.random.set_state(state)
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])