In [2]:
#1
import numpy as np

In [3]:
#2
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fedor/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fedor/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fedor/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fedor/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fedor/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fedor/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fedor/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fedor/anaconda3/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POP

In [4]:
#3
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#4
Z = np.ones(10)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
#task 5
Z = np.full(10, 2.5)
print(Z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [7]:
#task 6 
# Сделано в командной строке
python3 -c "import numpy; numpy.info(numpy.add)"


SyntaxError: invalid syntax (1373184828.py, line 1)

In [8]:
#task 7
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
#task 8
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
